# En local :
# docker build -f Dockerfile --progress=plain -t shinysbm:latest .
# docker run -p 38:38 shinysbm:latest
# then : localhost:38

image: docker:20.10.16

services:
  - docker:20.10.16-dind

stages:
  - build

docker-build:
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  # Default branch leaves tag empty (= latest tag)
  # All other branches are tagged with the escaped branch name (commit ref slug)
  script:
    - docker build -f Dockerfile --progress=plain -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

  # Run this job in a branch where a Dockerfile exists
  only:
    - tags
  tags:
    - stable

